name: sprint-planning
description: 'Generate sprint status tracking from epics. Use when the user says "run sprint planning" or "generate sprint plan"'
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
current_story_dir: "{config_source}:current_story_dir"
current_epics_dir: "{config_source}:current_epics_dir"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-planning"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/sprint-status-template.yaml"
validation: "{installed_path}/checklist.md"

# Variables and inputs
project_context: "**/project-context.md"
project_name: "{config_source}:project_name"

# Tracking system configuration
tracking_system: "file-system" # Options: file-system, Future will support other options from config of mcp such as jira, linear, trello
project_key: "NOKEY" # Placeholder for tracker integrations; file-system uses a no-op key
story_location: "{current_story_dir}" # Relative path for file-system, Future will support URL for Jira/Linear/Trello
story_location_absolute: "{current_story_dir}" # Absolute path for file operations

# Source files (file-system only)
epics_location: "{current_epics_dir}" # Directory containing epic*.md files
epics_pattern: "epic*.md" # Pattern to find epic files

# Output configuration
status_file: "{current_story_dir}/sprint-status.yaml"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: FULL LOAD - sprint planning needs ALL epics to build complete status
input_file_patterns:
  epics:
    description: "All epics with user stories"
    whole: "{current_epics_dir}/*.md"
    sharded: "{current_epics_dir}/**/*.md"
    load_strategy: "FULL_LOAD"

# Output configuration
default_output_file: "{status_file}"
