default: true

MD013: false
MD024: false
MD033: false
MD041: false
MD007: false
MD022: false
MD023: false
MD029: false
MD031: false
MD032: false
MD034: false
MD036: false
MD038: false
MD040: false
MD047: false
MD060: false
