extends: default

ignore: |
  node_modules/
  dist/
  BMAD-METHOD/
  .beads/
  reference/BMAD/research/
  .claude-trace/

rules:
  comments: disable
  document-start: disable
  empty-lines: disable
  new-lines: disable
  line-length: disable
  truthy:
    check-keys: false
