name: Check BMAD-METHOD Updates

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0

      - name: Check for upstream updates
        id: check
        run: |
          cd BMAD-METHOD
          git fetch origin main

          CURRENT=$(git rev-parse HEAD)
          UPSTREAM=$(git rev-parse origin/main)

          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          echo "upstream=$UPSTREAM" >> $GITHUB_OUTPUT

          if [ "$CURRENT" != "$UPSTREAM" ]; then
            echo "has_updates=true" >> $GITHUB_OUTPUT

            echo "## Changes in BMAD-METHOD" > /tmp/changelog.md
            echo "" >> /tmp/changelog.md
            echo "**Current:** \`${CURRENT:0:7}\`" >> /tmp/changelog.md
            echo "**Upstream:** \`${UPSTREAM:0:7}\`" >> /tmp/changelog.md
            echo "" >> /tmp/changelog.md
            echo "### Commits" >> /tmp/changelog.md
            echo "" >> /tmp/changelog.md
            git log --oneline $CURRENT..$UPSTREAM >> /tmp/changelog.md
            echo "" >> /tmp/changelog.md
            echo "### Changed Files" >> /tmp/changelog.md
            echo "" >> /tmp/changelog.md
            echo '```' >> /tmp/changelog.md
            git diff --stat $CURRENT..$UPSTREAM >> /tmp/changelog.md
            echo '```' >> /tmp/changelog.md
          else
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue for updates
        if: steps.check.outputs.has_updates == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const changelog = fs.readFileSync('/tmp/changelog.md', 'utf8');

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'bmad-update'
            });

            if (issues.data.length > 0) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issues.data[0].number,
                body: `## Update Check - ${new Date().toISOString().split('T')[0]}\n\n${changelog}`
              });
            } else {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'BMAD-METHOD has upstream updates available',
                body: `The upstream BMAD-METHOD repository has new changes.\n\n${changelog}`,
                labels: ['bmad-update', 'dependencies']
              });
            }
