name: GitHub Drift Check

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths:
      - '.github/**'
      - 'src/github/**'
      - 'src/root/**'
      - 'tools/check-github-drift.js'
      - 'tools/check-root-drift.js'
  push:
    branches: [main, develop]
    paths:
      - '.github/**'
      - 'src/github/**'
      - 'src/root/**'
      - 'tools/check-github-drift.js'
      - 'tools/check-root-drift.js'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  drift-check:
    name: Verify Config Sync
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: '20'

      - name: Verify .github drift
        run: node tools/check-github-drift.js

      - name: Verify root-file drift
        run: node tools/check-root-drift.js
