name: Quality Checks

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.ico'
      - '**/*.webp'
      - '**/*.pdf'
  push:
    branches: [main, develop]
    paths-ignore:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.ico'
      - '**/*.webp'
      - '**/*.pdf'

env:
  ALLOWED_LICENSES: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD, Unlicense, WTFPL, CC0-1.0, CC-BY-3.0, CC-BY-4.0, Python-2.0, PSF-2.0, MPL-2.0

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Pre-Push Validation
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Basic validation
        run: |
          echo "Checking for common issues..."
          for f in CLAUDE.md .coderabbit.yaml greptile.json; do
            if [ -f "$f" ]; then
              echo "✓ $f exists"
            else
              echo "::warning::Missing $f"
            fi
          done

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run canonical repository check
        run: npm run check

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check for merge conflict markers
        run: |
          # Use anchored patterns to avoid false positives
          if grep -rn "^<<<<<<<\|^=======\$\|^>>>>>>>" --include="*.md" --include="*.py" --include="*.ts" --include="*.js" --include="*.json" . 2>/dev/null; then
            echo "::error::Merge conflict markers found"
            exit 1
          fi
          echo "No merge conflict markers found"

      - name: Check for hardcoded secrets
        run: |
          echo "Scanning for potential secrets..."
          FOUND=0
          SECRET_MATCHES="$(grep -rn "PRIVATE.KEY\|-----BEGIN.*PRIVATE\|sk-[a-zA-Z0-9]\{20,\}\|ghp_[a-zA-Z0-9]\{36\}\|gho_[a-zA-Z0-9]\{36\}\|api[_-]?key.*['\"][a-zA-Z0-9]\{20,\}" --include="*.py" --include="*.ts" --include="*.js" --include="*.json" --include="*.yaml" --include="*.yml" . 2>/dev/null | grep -v node_modules | grep -v ".example" | grep -vE '(^|/)(\.github|src/github)/workflows/quality-checks\.yml:' | head -10 || true)"
          if [ -n "$SECRET_MATCHES" ]; then
            echo "$SECRET_MATCHES"
            echo "::warning::Potential hardcoded secrets detected - please review"
            FOUND=1
          fi

          AWS_MATCHES="$(grep -rn "AKIA[0-9A-Z]\{16\}" --include="*.py" --include="*.ts" --include="*.js" --include="*.json" . 2>/dev/null | grep -v node_modules | grep -v "test" | grep -v "example" | grep -v "fixture" | grep -v ".github/" | head -5 || true)"
          if [ -n "$AWS_MATCHES" ]; then
            echo "$AWS_MATCHES"
            echo "::warning::AWS access key pattern found - please review"
            FOUND=1
          fi

          if [ "$FOUND" -eq 1 ]; then
            echo "::error::Secret patterns detected - review findings above"
            exit 1
          fi
          echo "Secret scan complete"

  docs-audit:
    name: Documentation Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Check documentation freshness
        run: |
          echo "Checking documentation freshness..."
          CUTOFF_DATE=$(date -d "30 days ago" +%s 2>/dev/null || date -v-30d +%s)
          STALE_DOCS=0
          for file in $(git ls-files "*.md"); do
            LAST_COMMIT=$(git log -1 --format=%ct -- "$file" 2>/dev/null || echo "0")
            if [ "$LAST_COMMIT" -lt "$CUTOFF_DATE" ]; then
              STALE_DOCS=$((STALE_DOCS + 1))
            fi
          done
          echo "Found $STALE_DOCS markdown files not updated in 30+ days"
          if [ "$STALE_DOCS" -gt 5 ]; then
            echo "::warning::Found $STALE_DOCS potentially stale documentation files"
          fi

  syntax-check:
    name: Syntax Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Validate JSON/YAML
        uses: GrantBirki/json-yaml-validate@4b493a196a711807aec01c5ace08147f21b025bd

      - name: Lint GitHub Actions workflows
        uses: rhysd/actionlint@2df6872d4bde2b030214429d65f7aeee79ceee47
        with:
          args: -color

  editorconfig-check:
    name: EditorConfig
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check EditorConfig
        uses: editorconfig-checker/action-editorconfig-checker@ff2b7f22fb3dfdca5c54339c3ade98b0b3327ae6

  license-review:
    name: License Compliance
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: recursive

      - name: Check dependency licenses
        uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803
        with:
          allow-licenses: ${{ env.ALLOWED_LICENSES }}

      - name: Check submodule repository licenses
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail

          if [ ! -f .gitmodules ]; then
            echo "No .gitmodules file found; skipping submodule license checks."
            exit 0
          fi

          ALLOWED_SPDX="${ALLOWED_LICENSES//,/ }"
          NOASSERTION_ALLOWED_REPOS="bmad-code-org/BMAD-METHOD bmad-code-org/bmad-builder bmad-code-org/bmad-method-test-architecture-enterprise bmad-code-org/bmad-module-creative-intelligence-suite bmad-code-org/bmad-method-wds-expansion BlackUnicornSecurity/BMAD-CYBERSEC Hidden-History/pov-oversight-agent"

          while read -r _ url; do
            repo="$url"
            case "$repo" in
              https://github.com/*)
                repo="${repo#https://github.com/}"
                ;;
              http://github.com/*)
                repo="${repo#http://github.com/}"
                ;;
              git@github.com:*)
                repo="${repo#git@github.com:}"
                ;;
              ssh://git@github.com/*)
                repo="${repo#ssh://git@github.com/}"
                ;;
              *)
                echo "::error::Unsupported submodule URL format: ${url}"
                exit 1
                ;;
            esac
            repo="${repo%.git}"
            spdx="$(gh api "repos/${repo}" --jq '.license.spdx_id // "NOASSERTION"')"

            echo "${repo}: ${spdx}"

            if [ "$spdx" = "NOASSERTION" ]; then
              if echo " ${NOASSERTION_ALLOWED_REPOS} " | grep -Fq " ${repo} "; then
                echo "::warning::License SPDX is NOASSERTION for reviewed submodule ${repo}"
                continue
              fi
            fi

            if ! echo " ${ALLOWED_SPDX} " | grep -Fq " ${spdx} "; then
              echo "::error::Disallowed submodule license for ${repo}: ${spdx}"
              exit 1
            fi
          done < <(git config --file .gitmodules --get-regexp '^submodule\..*\.url$')
