# Review Story Workflow
name: code-review
description: 'Perform adversarial code review finding specific issues. Use when the user says "run code review" or "review this code"'

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"
current_story_dir: "{config_source}:current_story_dir"
current_epics_dir: "{config_source}:current_epics_dir"
current_architecture_dir: "{config_source}:current_architecture_dir"
current_ux_dir: "{config_source}:current_ux_dir"
sprint_status: "{current_story_dir}/sprint-status.yaml"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/code-review"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"
template: false

project_context: "**/project-context.md"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the specific epic needed for this story review
input_file_patterns:
  architecture:
    description: "System architecture for review context"
    whole: "{current_architecture_dir}/*.md"
    sharded: "{current_architecture_dir}/**/*.md"
    load_strategy: "FULL_LOAD"
  ux_design:
    description: "UX design specification (if UI review)"
    whole: "{current_ux_dir}/*.md"
    sharded: "{current_ux_dir}/**/*.md"
    load_strategy: "FULL_LOAD"
  epics:
    description: "Epic containing story being reviewed"
    whole: "{current_epics_dir}/*.md"
    sharded_index: "{current_epics_dir}/**/index.md"
    sharded_single: "{current_epics_dir}/**/epic-{{epic_num}}.md"
    load_strategy: "SELECTIVE_LOAD"
