import { promises as fs } from 'fs';
import path from 'path';
import yaml from 'js-yaml';

async function pathExists(p) {
  try {
    await fs.stat(p);
    return true;
  } catch (err) {
    if (err.code === 'ENOENT') return false;
    throw err;
  }
}

function renderYaml(moduleCode, values) {
  const header = [
    `# ${moduleCode.toUpperCase()} Module Configuration`,
    `# Generated by compass-engine init`,
    `# Date: ${new Date().toISOString()}`,
    '',
  ].join('\n');
  const body = yaml.dump(values, {
    noRefs: true,
    sortKeys: false,
    lineWidth: 200,
  });
  return `${header}\n${body}`;
}

export async function writeConfig(projectRoot, moduleCode, values, options = {}) {
  const { force = false } = options;
  const absDir = path.join(projectRoot, '_bmad', moduleCode);
  const absFile = path.join(absDir, 'config.yaml');

  if (await pathExists(absFile)) {
    if (!force) {
      throw new Error(
        `Config already exists at ${absFile}; refusing to overwrite. Pass --force to replace it.`,
      );
    }
  }

  await fs.mkdir(absDir, { recursive: true });
  await fs.writeFile(absFile, renderYaml(moduleCode, values), 'utf-8');
  return absFile;
}

export async function ensureDirectories(paths) {
  const created = [];
  for (const p of paths) {
    await fs.mkdir(p, { recursive: true });
    created.push(p);
  }
  return created;
}
