name: init-docs
description: 'Initialize Compass opinionated docs layout from existing project documentation. Use when the user says "initialize docs", "migrate docs", or "set up docs structure".'
author: "Compass"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
docs_root: "{config_source}:docs_root"
docs_human_root: "{config_source}:docs_human_root"
docs_human_policies_dir: "{config_source}:docs_human_policies_dir"
docs_human_templates_dir: "{config_source}:docs_human_templates_dir"
docs_human_overrides_file: "{config_source}:docs_human_overrides_file"
docs_ai_root: "{config_source}:docs_ai_root"
docs_architecture_dir: "{config_source}:docs_architecture_dir"
docs_architecture_decisions_dir: "{config_source}:docs_architecture_decisions_dir"
docs_development_dir: "{config_source}:docs_development_dir"
docs_getting_started_dir: "{config_source}:docs_getting_started_dir"
docs_guides_dir: "{config_source}:docs_guides_dir"
docs_reference_dir: "{config_source}:docs_reference_dir"
docs_tmp_migration_root: "{config_source}:docs_tmp_migration_root"
docs_tmp_cleanup_enabled: "{config_source}:docs_tmp_cleanup_enabled"
docs_framework_root: "{config_source}:docs_framework_root"
docs_framework_human_policies_dir: "{config_source}:docs_framework_human_policies_dir"
docs_framework_human_templates_dir: "{config_source}:docs_framework_human_templates_dir"
docs_framework_ai_root: "{config_source}:docs_framework_ai_root"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/documentation/init-docs"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Existing native scanners retained for extraction support
legacy_full_scan_instructions: "{project-root}/_bmad/bmm/workflows/document-project/workflows/full-scan-instructions.md"
legacy_deep_dive_instructions: "{project-root}/_bmad/bmm/workflows/document-project/workflows/deep-dive-instructions.md"
legacy_requirements_csv: "{project-root}/_bmad/bmm/workflows/document-project/documentation-requirements.csv"

# Output
migration_manifest: "{docs_reference_dir}/docs-migration-manifest-{date}.md"
default_output_file: "{docs_reference_dir}/docs-initialization-report-{date}.md"
